In [1]:
import numpy as np

In [2]:
def batch_norm(X, gamma, beta):
  X_batch_norm = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
  Y = gamma * X_batch_norm + beta
  return Y

In [3]:
def layer_norm(X, gamma, beta):
  X_layer_norm = (X - np.mean(X, axis=1)) / np.std(X, axis=1)
  Y = gamma * X_layer_norm + beta
  return Y

In [4]:
X = np.array([
  [20, 17, 32, 42, 65],
  [13, 65, 96, 53, 21],
  [45, 63, 74, 38, 64],
  [23, 76, 40, 34, 26],
  [14, 66, 78, 49, 23]
])

In [5]:
gamma = 1
beta = 0

In [6]:
print('batch normalization aoutput:\n\n', batch_norm(X, gamma, beta)) 

batch normalization aoutput:

 [[-0.25839036 -1.95226042 -1.32416942 -0.17220347  1.24551178]
 [-0.8613012   0.36725691  1.32416942  1.40632837 -0.92919133]
 [ 1.89486265  0.27061036  0.41380294 -0.74621505  1.19608671]
 [ 0.          0.89881297 -0.99312707 -1.32022663 -0.68206597]
 [-0.77517108  0.41558019  0.57932412  0.83231679 -0.83034119]]


In [7]:
print('layer normalization aoutput:\n\n', layer_norm(X, gamma, beta)) 

layer normalization aoutput:

 [[-0.87558998 -1.07958858 -1.87064621  0.11541284  0.77748801]
 [-1.27882221  0.5099897   2.95682788  0.69247703 -1.02301054]
 [ 0.56452512  0.44375727  1.29738366 -0.09442869  0.73656759]
 [-0.70277617  0.87426805 -1.26721195 -0.30427021 -0.81840843]
 [-1.22121761  0.54310591  1.59910079  0.48263551 -0.9411697 ]]
